services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/data.csv:/app/data.csv  # Monte le fichier CSV dans le conteneur
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
