services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/data:/app/data
    environment:
      NODE_ENV: production
    command: ["npm", "start"]

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    command: ["npm", "run", "start"]
