services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/data.csv:/app/data.csv
    environment:
      NODE_ENV: production
    command: ["npm", "start"]

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    command: ["npm", "run", "start"] # Assurez-vous que le script 'start' est correct
