name: Java CI/CD Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile Java classes
        run: |
          mkdir -p javatp/target/classes
          javac -d javatp/target/classes javatp/src/main/java/javatp/*.java

      - name: Run Java application
        run: java -cp javatp/target/classes javatp.Main

      - name: Install dependencies and run tests
        run: mvn -f javatp/pom.xml clean verify

      - name: Package application
        run: mvn -f javatp/pom.xml package

      - name: Archive JAR file
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: javatp/target/app-1.0-SNAPSHOT-jar-with-dependencies.jar
