name: Run Pytest

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  pytest:
    runs-on: ubuntu-24.04

    steps:
    # Vérifie le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Installe les dépendances Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Exécute pytest
    - name: Run Pytest
      run: pytest
